apiVersion: integration/v1
kind: Trigger
name: json
version: 1
summary: Receive a webhook
description: |
  This trigger receives a generic webhook and passes through a JSON object 
  sent as an HTTP request body as Relay event.

responders:
- webhook

schemas:
  spec: {}
  event:
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object

examples:
- summary: Receive a webhook
  content:
    apiVersion: v1
    kind: Trigger
    name: generic-webhook
    source:
      type: webhook
      image: relaysh/stdlib-trigger-json
    binding:
      parameters:
        foo: !Data foo

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/stdlib-trigger-json
